@hms-backend_HostAddress = https://localhost:7172
@backend_address = https://localhost:7172

###

POST {{backend_address}}/api/user/login
Content-Type: application/json

{
  "email": "admin@hms.com",
  "password": "Admin@123"
}

###

POST {{backend_address}}/api/user/add-user
Authorization: {{$apiKey}}
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "firstName": "John",
  "lastName": "Doe",
  "dob": "2025-06-30",
  "address": "789 Oak Avenue, Springfield",
  "supervisorID": "s9t8u7v6-w5x4-3210-yzab-9876543210cd",
  "contactNumber": "+11234567890",
  "password": "ThisisAStr0ngPassword$",
  "role": "Supervisor"
}


###
